apiVersion: v2
appVersion: "1.0"
description: A Helm chart for CCD Case Document AM API
name: ccd-case-document-am-api
home: https://github.com/hmcts/ccd-case-document-am-api
version: 1.6.17
maintainers:
  - name: CCD Team
dependencies:
  - name: java
    version: 3.6.0
    repository: '@hmctspublic'
