apiVersion: v2
appVersion: "1.0"
description: A Helm chart for CCD Case Document AM API
name: ccd-case-document-am-api
home: https://github.com/hmcts/ccd-case-document-am-api
version: 1.7.15
maintainers:
  - name: CCD Team
dependencies:
  - name: java
    version: 5.2.1
    repository: 'https://hmctspublic.azurecr.io/helm/v1/repo/'
