apiVersion: v1
appVersion: "1.0"
description: A Helm chart for CCD Case Document AM API
name: ccd-case-document-am-api
home: https://github.com/hmcts/ccd-case-document-am-api
version: 0.3.0
maintainers:
  - name: Access Management Team
